<?php 
    $id = isset($_GET['id']) ? $_GET['id'] : '';
    $student = $this->getStudent($id);

    $id = $student->getId();
    $firstname = $student->getFirstName(); 
    $lastname = $student->getLastName(); 
    $gender = $student->getGender(); 
    $email = $student->getEmail();
?>
<div>
    <h2><?= empty($id) ? 'Student Form' : 'Edit Form' ?></h2>
    <form action="<?= $this->getUrl('macapobres/student/save') ?>" method="post">
        <div>
            <label for="">First Name</label>
            <input type="text" name="first_name" id="" required="required" value="<?= $firstname  ?>">
        </div>
        <div>
            <label for="">Last Name</label>
            <input type="text" name="last_name" id="" required="required" value="<?=  $lastname ?>">
        </div>
        <div>
            <label for="">Gender</label>
            <input type="radio" name="gender" value="male" <?= $gender == 'male' ? 'checked' : '' ?>>Male
            <input type="radio" name="gender" value="female" <?= $gender == 'female' ? 'checked' : '' ?>>Female
        </div>
        <div>
            <label for="">Email</label>
            <input type="email" name="email" id="" value="<?= $email  ?>">
        </div>
        <div>
            <input type="hidden" name="id" value="<?= $id  ?>">
            <button type="submit">ADD</button>
            <a href="<?= $this->getUrl('macapobres/student/index') ?>">CANCEL</a>
        </div>
    </form>
</div>