<div>
    <div>
        <h2>List of user(s)</h2>
        <a href="<?= $block->getAddUserUrl() ?>">Add User</a>
    </div>
    <div>
        <table>
            <thead>
                <td>ID</td>
                <td>First Name</td>
                <td>Last Name</td>
                <td>Create At</td>
                <td>Actions</td>
            </thead>
            <tbody>
                <?php foreach($block->getUserCollection() as $user): ?>
                <tr>
                    <td><?= $user->getEntityId() ?></td>
                    <td><?= $user->getFirstName() ?></td>
                    <td><?= $user->getLastName() ?></td>
                    <td><?= $user->getCreatedAt() ?></td>
                    <td>
                        <a href="<?= $block->getEditUserUrl() .  'id/' . $user->getEntityId() . '/' ?>">Edit</a>
                        <a href="<?= $block->getDeleteUserUrl() .  'id/' . $user->getEntityId() . '/' ?>">Delete</a>
                    </td>
                </tr>

                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>